spring.application.name=profile-service
spring.data.mongodb.uri=mongodb://localhost:27017/profiledb
server.port=8081
cloudinary.cloud_name=qcfdctao
cloudinary.api_key=214834972428256
cloudinary.api_secret=JsmBcFIm_A2ofW97ae_iZMJPhV0